"""Apply reviewed, fail-closed integration changes to the pinned wire-pod source."""
from pathlib import Path
import sys

root = Path(sys.argv[1]) / 'chipper'
def replace(file, old, new):
    p = root / file
    text = p.read_text()
    if text.count(old) != 1:
        raise SystemExit(f'Upstream changed: {file}')
    p.write_text(text.replace(old, new))

# Keep administrative APIs on loopback. The LAN connCheck listener must not share
# the default mux (which includes configuration, robot control and scripting).
replace('pkg/wirepod/config-ws/webserver.go', 'http.ListenAndServe(":"+vars.WebPort, nil)', 'http.ListenAndServe("127.0.0.1:"+vars.WebPort, nil)')
replace('pkg/wirepod/sdkapp/server.go', 'http.ListenAndServe(":80", nil)', 'http.ListenAndServe(vars.GetOutboundIP().String()+":80", connCheckMux())')
p = root / 'pkg/wirepod/sdkapp/server.go'
p.write_text(p.read_text() + '''
func connCheckMux() *http.ServeMux {
    mux := http.NewServeMux()
    mux.HandleFunc("/ok", connCheck)
    mux.HandleFunc("/ok:80", connCheck)
    return mux
}
''')
# Route-selected LAN address, not the default Internet/VPN interface.
replace('pkg/vars/vars.go', 'func GetOutboundIP() net.IP {', '''func GetOutboundIP() net.IP {
    if ip := net.ParseIP(os.Getenv("VECTOR_HOST_IP")); ip != nil { return ip }
''')
replace('pkg/initwirepod/startserver.go', 'tls.Listen("tcp", ":"+vars.APIConfig.Server.Port', 'tls.Listen("tcp", vars.GetOutboundIP().String()+":"+vars.APIConfig.Server.Port')
# mDNS restricted to the robot interface and a clean shutdown, rather than
# advertising on VPN/cable interfaces. Wrapper owns this registration.
# Reject broken plugin builds before binding/advertising the voice server.
replace('pkg/wirepod/preqs/server.go', 'ttr.LoadPlugins()', '''ttr.LoadPlugins()
    if len(ttr.PluginNames) != 1 || ttr.PluginNames[0] != "Dimensional HumanCLI" {
        return nil, fmt.Errorf("the bundled HumanCLI plugin did not load")
    }
    fmt.Println("DIMENSIONAL_PLUGIN_READY")''')
# Use app transcription, retaining upstream audio decoding/VAD/native intents.
p = root / 'pkg/wirepod/stt/whisper/Whisper.go'
s = p.read_text().replace('"mime/multipart"', '"net/url"\n    "fmt"\n    "time"')
s = s.replace('if os.Getenv("OPENAI_KEY") == "" {', 'if os.Getenv("DIMENSIONAL_VOICE_CONFIG") == "" {')
a = s.index('func makeOpenAIReq('); b = s.index('\nfunc STT(', a)
s = s[:a] + '''func makeOpenAIReq(in []byte, serial string) (string, error) {
    var cfg struct { URL string `json:"url"`; TokenFile string `json:"token_file"` }
    raw, err := os.ReadFile(os.Getenv("DIMENSIONAL_VOICE_CONFIG"))
    if err != nil { return "", fmt.Errorf("voice bridge configuration unavailable") }
    if json.Unmarshal(raw, &cfg) != nil { return "", fmt.Errorf("invalid voice configuration") }
    u, err := url.Parse(cfg.URL)
    if err != nil || u.Scheme != "http" || u.Hostname() != "127.0.0.1" || u.Port() == "" || u.User != nil || u.Path != "" || u.RawQuery != "" || u.Fragment != "" {
        return "", fmt.Errorf("voice bridge must use loopback")
    }
    token, err := os.ReadFile(cfg.TokenFile)
    if err != nil { return "", fmt.Errorf("voice bridge credential unavailable") }
    request, err := http.NewRequest("POST", cfg.URL+"/api/vector/wirepod/audio", bytes.NewReader(in))
    if err != nil { return "", err }
    request.Header.Set("Content-Type", "audio/wav")
    request.Header.Set("X-Go2-Request", "1")
    request.Header.Set("X-Vector-Serial", serial)
    request.Header.Set("Authorization", "Bearer "+strings.TrimSpace(string(token)))
    client := &http.Client{Timeout: 50*time.Second, CheckRedirect: func(r *http.Request, via []*http.Request) error { return http.ErrUseLastResponse }}
    response, err := client.Do(request)
    if err != nil { return "", fmt.Errorf("app transcription unavailable") }
    defer response.Body.Close()
    if response.StatusCode != 200 { return "", fmt.Errorf("app transcription refused (%d)", response.StatusCode) }
    var result openAiResp
    if json.NewDecoder(io.LimitReader(response.Body, 16384)).Decode(&result) != nil { return "", fmt.Errorf("invalid transcription response") }
    return result.Text, nil
}
''' + s[b:]
s = s.replace('transcribedText := strings.ToLower(makeOpenAIReq(pcmBuf))', 'text, err := makeOpenAIReq(pcmBuf, req.Device)\n    if err != nil { return "", err }\n    transcribedText := strings.ToLower(text)')
p.write_text(s)

# Keep SDK config generated by wire-pod in its private app data, not the user's
# unrelated global SDK installation.
replace('pkg/vars/vars.go', 'logger.Println("SDK info path: " + SDKIniPath)', 'SDKIniPath = "./sdk-config/"\n    os.MkdirAll(SDKIniPath, 0700)\n    logger.Println("SDK info path: " + SDKIniPath)')
