"""English presentation of system messages written by earlier app versions."""

LEGACY = {
    "Solo se permite acceso local": "Local access only",
    "Falta encabezado de la consola local": "Local console request header is missing",
    "Sin cámara": "No camera available",
    "No se reproduce una grabación abierta": "Save the recording before replaying it",
    "Antes de desconectar, acostá el Go2 y confirmá visualmente que está apoyado": "Before disconnecting, lie Go2 down and visually confirm it is supported",
    "Detené el movimiento antes de confirmar la desconexión": "Stop movement before confirming disconnection",
    "Go2 desconectado": "Go2 disconnected",
    "Go2 conectado": "Go2 connected",
    "Parada solicitada": "Stop requested",
    "Seleccioná una grabación DimOS .db existente": "Select an existing DimOS .db recording",
    "La grabación no tiene LiDAR": "The recording has no LiDAR",
    "No hay espacio suficiente para copiar la grabación": "Not enough disk space to copy the recording",
    "Grabación importada como copia independiente": "Recording imported as an independent copy",
    "Pausá el movimiento antes de generar un mapa": "Pause movement before generating a map",
    "El archivo todavía no existe": "The file does not exist yet",
    "Ruta no permitida o archivo ausente": "Path not allowed or file missing",
    "No es un archivo": "Not a file",
    "La aplicación se reinició durante la generación.": "The app restarted during map generation.",
    "No existe ese elemento": "Item not found",
    "Tipo de elemento incorrecto": "Incorrect item type",
    "El nombre debe tener entre 1 y 80 caracteres": "Name must contain between 1 and 80 characters",
    "El planificador detectó un obstáculo y detuvo la maniobra.": "The planner detected an obstacle and stopped the maneuver.",
    "El planificador detectó falta de avance y vuelve a calcular.": "The planner detected no progress and is replanning.",
    "No se encontró una ruta segura al destino.": "No safe route to the goal was found.",
    "Recalculando la ruta.": "Recalculating the route.",
    "Se encontró una ruta al destino.": "A route to the goal was found.",
    "Exploración eligió un nuevo destino.": "Exploration selected a new goal.",
    "El destino agotó su tiempo; exploración busca otro.": "The goal timed out; exploration is choosing another.",
    "Se envía giro, pero no se detecta rotación durante al menos 4 s.": "Rotation commands are being sent, but no rotation has been observed for at least 4 s.",
    "Se envía avance, pero no se detecta desplazamiento durante al menos 4 s.": "Movement commands are being sent, but no displacement has been observed for at least 4 s.",
    "Esperando destino": "Waiting for a goal",
    "Todavía no hay una maniobra de navegación confirmada.": "No navigation maneuver has been confirmed yet.",
    "Buscando ruta": "Finding a route",
    "Exploración seleccionó un sector por recorrer.": "Exploration selected an area to visit.",
    "Ruta encontrada": "Route found",
    "El planificador encontró un recorrido hacia el destino.": "The planner found a route to the goal.",
    "Girando para tomar la ruta": "Turning to follow the route",
    "Primero orienta el robot; todavía no pide avance.": "The robot is aligning first; forward motion has not been requested yet.",
    "Siguiendo la ruta": "Following the route",
    "El planificador está enviando órdenes de desplazamiento.": "The planner is sending movement commands.",
    "Ajustando orientación final": "Adjusting final orientation",
    "Llegó a la posición y está orientándose.": "The robot reached the position and is aligning.",
    "Recalculando ruta": "Recalculating route",
    "Está buscando un recorrido actualizado.": "Looking for an updated route.",
    "Sin ruta segura": "No safe route",
    "No encontró un paso al destino en el mapa actual.": "No route to the goal was found in the current map.",
    "Destino alcanzado": "Goal reached",
    "El planificador informó que terminó el recorrido.": "The planner reported the route is complete.",
    "Control manual": "Manual control",
    "El movimiento depende del teclado o de los botones.": "Movement is controlled by the keyboard or buttons.",
    "Navegación en pausa": "Navigation paused",
    "No hay una misión autónoma activa.": "No autonomous mission is active.",
    "Error de DimOS": "DimOS error",
    "Desconectá la sesión actual primero": "Disconnect the current session first",
    "Ingresá la IP privada del Go2 en tu Wi-Fi": "Enter Go2's private IP address on your Wi-Fi",
    "Replay solicitado": "Replay requested",
    "Conexión al Go2 solicitada": "Go2 connection requested",
    "Go2 no responde en ": "Go2 is not responding at ",
    ". Reintentando; verificá la IP si cambió por DHCP.": ". Retrying; check whether DHCP changed its IP address.",
    "El proceso de DimOS terminó. Consultá runtime.log.": "The DimOS process exited. Check runtime.log.",
    "DimOS no respondió; reiniciando la conexión.": "DimOS did not respond; restarting the connection.",
    "No se pudo guardar la IP del Go2": "Could not save Go2's IP address",
    "Replay listo": "Replay ready",
    "Dejaron de llegar posiciones del robot.": "Robot position updates stopped arriving.",
    "Grabación detenida por error o poco espacio en disco": "Recording stopped due to an error or low disk space",
    "El Go2 no está conectado": "Go2 is not connected",
    "Esperá a que llegue el mapa navegable": "Wait for the navigation map",
    "Ya hay una sesión de grabación": "A recording session is already active",
    "Conectá el Go2 o un replay primero": "Connect Go2 or a replay first",
    "Se necesitan al menos 3 GB libres": "At least 3 GB of free space is required",
    "No hay grabación activa": "No recording is active",
    "Resolución admitida: 0.05 o 0.1 m": "Supported resolution: 0.05 or 0.1 m",
    "Cerrá la grabación antes de generar el mapa": "Save the recording before generating the map",
    "PGO requiere poses para al menos el 80% de las nubes LiDAR": "PGO requires poses for at least 80% of LiDAR clouds",
    "Ya hay una generación en curso": "Map generation is already running",
    "El generador terminó con código ": "Map generator exited with code ",
    ". Revisá generation.log.": ". Check generation.log.",
    "La exportación a Rerun excedió 120 segundos": "Rerun export exceeded 120 seconds",
    "Mapa generado y guardado": "Map generated and saved",
    "El trabajo ya terminó": "The job has already finished",
    "Postura inválida": "Invalid posture",
    "El Go2 no confirmó la postura (API ": "Go2 did not confirm posture (API ",
    ", código ": ", code ",
    "Liberá la parada antes de levantar el Go2": "Release stop before standing Go2 up",
    "Se interrumpió Levantarse; no se habilitó la marcha": "Stand up was interrupted; walking was not enabled",
    "Modo desconocido": "Unknown mode",
    "Primero liberá la parada": "Release stop first",
    "Velocidad inválida": "Invalid velocity",
    "La instrucción perdió el control del robot": "The instruction lost control of the robot",
    "Comando desconocido": "Unknown command",
    "No existe la grabación": "Recording does not exist",
    "Datos disponibles para inspección": "Data available for inspection",
    "Sin LiDAR": "No LiDAR",
    "La cobertura total requiere conocer los límites del espacio.": "Total coverage requires a reference for the boundaries of the space.",
    "La precisión absoluta requiere una referencia externa.": "Absolute accuracy requires an external reference.",
    "Un mapa exportado no garantiza relocalización entre reinicios del robot.": "An exported map does not guarantee relocalization after robot restarts.",
    "La API key de OpenAI no tiene un formato válido": "The OpenAI API key format is invalid",
    "Ingresá tu API key para habilitar las consultas visuales": "Enter your API key to enable visual questions",
    "Configurá la API key y habilitá visión en HumanCLI para preguntar qué ve el Go2": "Configure your API key and enable HumanCLI vision to ask what Go2 sees",
    "No se pudo contactar a OpenAI. Revisá la conexión e intentá de nuevo": "Could not contact OpenAI. Check your connection and try again",
    "API key inválida": "Invalid API key",
    "cuota o límite de solicitudes alcanzado": "Quota or request limit reached",
    "OpenAI no devolvió una descripción. Intentá de nuevo": "OpenAI returned no description. Try again",
    "Usá una instrucción simple: «avanzá 2 metros», «andá hasta el fondo» o «andá a la izquierda».": "Use a single instruction: “walk 2 meters”, “go to the far end”, or “move left”.",
    "HumanCLI local reconoce direcciones y distancias. Probá «avanzá 2 metros» o «andá hasta el fondo».": "Local HumanCLI recognizes directions and distances. Try “walk 2 meters” or “go to the far end”.",
    "Indicá una sola dirección": "Specify one direction",
    "La distancia debe estar entre 0,2 y 5 metros": "Distance must be between 0.2 and 5 meters",
    "No hay un corredor libre conocido en esa dirección. Mapeá un poco más por teleop.": "There is no known clear corridor in that direction. Map more of the space using Teleop.",
    "La distancia solicitada sale del corredor libre conocido": "The requested distance extends beyond the known clear corridor",
    "Ya hay una consulta visual en curso": "A visual question is already in progress",
    "Seleccioná HumanCLI con el robot conectado": "Select HumanCLI with the robot connected",
    "No hay una imagen reciente de la cámara": "No recent camera image is available",
    "La instrucción pertenece a un control anterior": "This instruction belongs to an expired control session",
    "Todavía no hay mapa y posición suficientes": "Map and position data are not ready yet",
    "DimOS no aceptó el destino. Revisá el estado de navegación.": "DimOS did not accept the goal. Check navigation status.",
    "Movimiento detenido.": "Movement stopped.",
    "Destino solicitado a DimOS:": "Goal requested from DimOS:",
}


def english(text):
    if not isinstance(text, str):
        return text
    for source, target in sorted(LEGACY.items(), key=lambda item: -len(item[0])):
        text = text.replace(source, target)
    return text
